name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 21 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 28 days with no activity.'
          days-before-issue-stale: 21
          days-before-issue-close: 7
          days-before-pr-close: -1
          days-before-pr-stale: -1
          exempt-issue-labels: 'released on @beta'
          only-labels: 'waiting for reply'
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          close-issue-message: "This issue won't be fixed and was closed because it has been inactive for 7 days."
          days-before-issue-stale: -1
          days-before-issue-close: 7
          days-before-pr-close: -1
          days-before-pr-stale: -1
          exempt-issue-labels: 'released on @beta'
          only-labels: 'wontfix'
